title: Rituraj Tripathi
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Creative ideas stem from unconventional thinking, which I complement with smart work and dedication. I'm always in a mode of learning and capturing new insights.

# Author details for the jekyll-seo-tag gem
author:
  name: Rituraj Tripathi
  email: riturajtripathi138@gmail.com
  twitter: riturajtripathi139

# Social details for the jekyll-seo-tag gem
social:
  name: Rituraj Tripathi
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS
